version: "3"
#services를 컨테이너를 정의
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=development
    ports:
      - "8000:8000"
    command: ["nodemon", "-L", "server/index.js"] # 컨테이너가 시작될 때 실행할 명령
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/dist
    tty: true

volumes:
  build_folder: null
  elasticsearch:
  prometheus_data:
  grafana-data:
