version: "3"
#services를 컨테이너를 정의
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=development
    ports:
      - "8000:8000"
    command: ["nodemon", "-L", "server/index.js"] # 컨테이너가 시작될 때 실행할 명령
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/dist
    tty: true

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - build_folder:/var/www/frontend
      - ./nginx/log:/var/log/nginx

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ AMQP 포트
      - "15672:15672" # RabbitMQ 관리자 포트
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: always

  redis:
    image: "redis"
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
  redis-insight:
    image: "redislabs/redisinsight:latest"
    container_name: "my-redis-insight"
    ports:
      - "8001:8001"
    depends_on:
      - redis
volumes:
  build_folder: null
  elasticsearch:
  prometheus_data:
  grafana-data:
