version: "3"

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - ./data/:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=development
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/backend
      - /backend/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/dist
    tty: true

volumes:
  build_folder: null
